description: Setup Vagrant on GitHub actions agent (macOS only)
name: Setup Vagrant
runs:
    using: composite
    steps:
        # TODO: Fail if not macOS agent

        # Vagrant requires rsync tool when using synced_folder
        #   See https://www.vagrantup.com/docs/synced-folders/rsync#prerequisites
        - name: Install rsync (required for rsync typed synced_folder) [macos-* only]
          shell: bash
          run: brew install rsync
          if: ${{ startsWith(runner.name, 'macos-') }}

        # On macos-11, vagrant and virtualbox are not installed
        #   See https://github.com/actions/virtual-environments/issues/2999#issuecomment-812566316
        - name: Install vagrant and virtualbox [macos-11 only]
          shell: bash
          run: brew install --cask vagrant virtualbox
          if: ${{ runner.name == 'macos-11' }}

        # Disk size plugin seems to work fine with regard to resizing the primary disk
        #   See https://github.com/sprotheroe/vagrant-disksize
        #   Alternatively, we could use the experimental disks feature,
        #     but it requires setting the VAGRANT_EXPERIMENTAL environment variable
        - name: Install vagrant-disksize plugin [macos-* only]
          shell: bash
          run: vagrant plugin install vagrant-disksize
          if: ${{ startsWith(runner.name, 'macos-') }}

        # TODO: Setup vagrant sudoer

        # TODO: Maybe patch vagrant, see https://github.com/hashicorp/vagrant/issues/12583#issuecomment-985787134

