description: Run Gradle with Nokee cache
name: Gradle
inputs:
    working-directory:
        description: 'Gradle arguments'
        required: true
    run:
        description: 'Args'
        required: true
runs:
    using: composite
    steps:
        -   shell: bash
            run: vagrant ssh -c "${{ inputs.run }}"
            working-directory: ${{ inputs.working-directory }}.bak

