# -*- mode: ruby -*-
# vi: set ft=ruby :

#sudo pkg install -y openjdk8 llvm90 gcc9 bash tree git
$script = <<-SCRIPT
echo "cd /vagrant" >> /home/vagrant/.cshrc
pkg install -y openjdk8 llvm90 gcc9 bash tree git
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-12.3-STABLE"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
  config.vm.provision "shell", inline: $script
  config.vm.network "private_network", type: "dhcp"
#   config.vm.synced_folder "../../../", "/vagrant", type: "rsync"
  #config.disksize.size = "50GB"

  config.ssh.shell = "sh"
  #config.ssh.extra_args = ["-t", "cd /vagrant; sh"]

  # Manual Steps
  # - [ ] Resize Disk, see https://www.freebsd.org/doc/handbook/disks-growing.html
  #       NOTE: May need to start growfs service: % sudo service growfs onestart
  # - [ ] Install OpenJDK 8
  #       % sudo pkg install -y openjdk8
  # - [ ] Install Clang 9
  #       % sudo pkg install -y llvm90
  # - [ ] Install GCC 9
  #       % sudo pkg install -y gcc9
  # - [ ] Install Bash
  #       % sudo pkg install -y bash
  # - [ ] Install Vim
  #       % sudo pkg install -y vim
  # - [ ] Install GitLab Runner, see https://docs.gitlab.com/runner/install/freebsd.html
  # Follow up
  # - [ ] Install Git
  #       % sudo pkg install -y git
  # - [ ] Install Tree
  #       % sudo pkg install -y tree
end
