description: Run Gradle with Nokee cache
name: Gradle
inputs:
    working-directory:
        description: 'Gradle arguments'
        required: true
    arguments:
        description: 'Args'
        required: true
runs:
    using: composite
    steps:
        -   shell: bash
            run: vagrant ssh -c "./gradlew ${{ inputs.arguments }}"
            working-directory: ${{ inputs.working-directory }}

