description: Run Gradle with Nokee cache
name: Gradle
inputs:
    working-directory:
        description: 'Gradle arguments'
        required: true
runs:
    using: composite
    steps:
        -   name: Cache Vagrant boxes
            uses: actions/cache@v2
            with:
                path: |
                    ~/.vagrant.d/boxes
                    ~/VirtualBox VMs
                key: ${{ runner.os }}-vagrant-${{ hashFiles('${inputs.working-directory}/Vagrantfile') }}
                restore-keys: ${{ runner.os }}-vagrant-

        # TODO: Should have a post action that halt the machine
        -   name: Vagrant up
            shell: bash
            run: vagrant up
            working-directory: ${{ inputs.working-directory }}

