name: vagrant

on: [push]

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-vagrant
      - uses: ./.github/actions/vagrant-provision
        with:
          mem: 4096
          working-directory: .github/vagrant/freebsd-12.3
      - uses: ./.github/actions/vagrant-ssh
        with:
          working-directory: .github/vagrant/freebsd-12.3
          run: ./gradlew tasks
#      - run: vagrant halt
#        working-directory: .github/vagrant/freebsd-12.3

      # - run: brew install rsync

      # - name: Cache Vagrant boxes
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.vagrant.d/boxes
      #     key: ${{ runner.os }}-vagrant-${{ hashFiles('.github/vagrant/freebsd-12.3/Vagrantfile') }}
      #     restore-keys: |
      #       ${{ runner.os }}-vagrant-

      # - name: Show vagrant version
      #   run: vagrant --version

      # - name: Vagrant up
      #   run: vagrant up
      #   working-directory: .github/vagrant/freebsd-12.3

      # - name: SSH into box
      #   run: vagrant ssh -c "./gradlew help"
      #   working-directory: .github/vagrant/freebsd-12.3
