name: vagrant

on: [push]

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-vagrant
        with:
          install-vagrant-if: 'false'
          install-virtualbox-if: 'false'
      - uses: ./.github/actions/vagrant-provision
        with:
          mem: 4096
          name: freebsd-12.3
      - uses: ./.github/actions/vagrant-ssh
        with:
          name: freebsd-12.3
          run: ./gradlew tasks
